import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
    container: {
        height: "100%",
        backgroundColor: "#A78964",
    },
    container2: {
        padding: 24,

    },
    hd: {
        display: "flex",
        justifyContent: "space-between",
        flexDirection: 'row'
    },
    thd: {
        display: "flex",
        width: 175,
        height: 35,
        flexDirection: "column",
        justifyContent: "center",
        color: '#000',
        textAlign: "center",
        fontFamily: "Inter",
        fontSize: 30,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 35,
        letterSpacing: 0.16,
    },
    icon: {
        fontSize: 35,
        color: 'black',
    },
    img: {
        width: 235,
        height: 206,
        alignSelf: "center",
        marginTop: 27,
    },
    v3: {
        width: "100%",
        height: 638,
        flexShrink: 0,
        borderRadius: 40,
        backgroundColor: '#E9C08E',
        padding: 24,
    },
    t1: {
        marginTop: 42,
        display: "flex",
        width: 139,
        height: 35,
        flexDirection: "column",
        justifyContent: "center",
        flexShrink: 0,
        color: '#000',
        fontFamily: "Inter",
        fontSize: 20,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 21,
        letterSpacing: 0.16,
    },
    tip1: {
        padding: 10,
        display: "flex",
        width: "100%",
        height: 40,
        flexDirection: "column",
        justifyContent: "center",
        color: "#5B5B5B",
        fontFamily: "Inter",
        fontSize: 16,
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: 21,
        letterSpacing: 0.16,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,

    },
    vp: {
        position: 'relative'
    },
    t2: {
        marginTop: 23,
        display: "flex",
        width: 139,
        height: 35,
        flexDirection: "column",
        justifyContent: "center",
        flexShrink: 0,
        color: '#000',
        fontFamily: "Inter",
        fontSize: 20,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 21,
        letterSpacing: 0.16,
    },
    icon2: {
        display: "flex",
        position: 'absolute',
        alignSelf: "flex-end",
        margin: 5,
        right: 5,
        fontSize: 30,
    },
    t3: {
        display: "flex",
        width: 127,
        height: 25,
        flexDirection: "column",
        alignSelf: "flex-end",
        flexShrink: 0,
        color: "#263238",
        textAlign: "center",
        fontFamily: "Inter",
        fontSize: 13,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 24,
        letterSpacing: 0.16,
    },
    btn: {
        backgroundColor: "#D97700",
        display: "flex",
        width: 296,
        height: 70,
        flexDirection: "column",
        justifyContent: "center",
        borderRadius: 10,
        alignSelf: "center",
        marginTop: 37,
    },
    txtbtn: {
        color: "#FDFDFD",
        textAlign: "center",
        fontFamily: "Inter",
        fontSize: 20,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 21,
        letterSpacing: 0.16,
    },
    t4: {
        margin: 10,
        color: '#000',
        textAlign: "center",
        fontFamily: "Inter",
        fontSize: 20,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 21,
        letterSpacing: 0.16,
    },
    vic: {
        display: "flex",
        justifyContent: "space-around",
        flexDirection: 'row',
        width: "70%",
        alignSelf:"center",
    },
    icongg: {
        fontSize: 35,
        flexShrink: 0,
        color:"red"
    },
    iconap: {
        fontSize: 35,
        flexShrink: 0,
        color:'#000'
    },
    iconfb: {
        fontSize: 35,
        flexShrink: 0,
        color:"#1877F2"
    },
    txtlg: {
        display: "flex",
        justifyContent: "center",
        flexDirection: 'row',
        marginTop: 15,

    },
    t5: {
        color: '#000',
        textAlign: "center",
        fontFamily: "Inter",
        fontSize: 18,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 21,
        letterSpacing: 0.16,
    },
    tlg: {
        color: "#733F00",
        fontFamily: "Inter",
        fontSize: 18,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 21,
        letterSpacing: 0.16,
    },

})

