import {StyleSheet} from 'react-native';
import { BACKGROUND_BUTTON_COLOR } from '../../../utils/contanst';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  tenSanPhamVaGiaTienContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  giaTienContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  separateLine: {
    height: 1,
    width: '95%',
    backgroundColor: 'gray',
    marginVertical: 10,
  },
  textTenSanPham: {
    fontSize: 20,
    color: 'black',
    fontWeight: '500',
    marginLeft: 10,
    width: '50%',
  },
  textGiaTien: {
    fontSize: 16,
    color: 'black',
    fontWeight: '400',
    fontStyle: 'italic',
    textDecorationLine: 'line-through',
  },
  textGiaTienGiamGia: {
    fontSize: 18,
    color: 'red',
    fontWeight: '500',
    marginHorizontal: 10,
  },
  toppingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 10,
    borderBottomWidth: 0.3,

    marginLeft: 10,
    paddingVertical: 12,
  },
  textTopping: {
    fontSize: 15,
    color: 'black',
    fontWeight: '500',
  },
  giaTienContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  textHeaderTopping: {
    fontSize: 18,
    color: 'black',
    fontWeight: '500',
    marginHorizontal: 10,
    marginBottom: 1,
    marginTop: 5,
  },
  textHeaderDa: {
    fontSize: 18,
    color: 'black',
    fontWeight: '500',
    marginHorizontal: 10,
    marginBottom: 1,
    marginTop: 10,
  },
  textTien: {
    fontSize: 15,
    color: 'black',
    fontWeight: '400',
  },
  tienToppingContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  toppingChecked: {
    marginHorizontal: 10,
  },
  daContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: '#FDE7C9',
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: BACKGROUND_BUTTON_COLOR,
    width: 70,
  },
  daCheckedContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: BACKGROUND_BUTTON_COLOR,
    width: 70,
  },

  textDa: {
    fontSize: 15,
    color: 'black',
    fontWeight: '600',
  },
  textYeuCauThem: {
    fontSize: 15,
    color: 'black',
    fontWeight: '600',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  textDaChecked: {
    fontSize: 15,
    color: 'white',
    fontWeight: '500',
  },
  danhSachTopping: {
    width: '100%',
  },
  toppingHeaderContainer: {
    width: '100%',
    height: 'auto',
  },
  daHeaderContainer: {
    width: '100%',
  },
  danhSachDa: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginRight: 20,
    marginTop: 10,
  },
  chuThichContainer: {
    width: '95%',
    height: 50,
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: BACKGROUND_BUTTON_COLOR,
    marginHorizontal: 10,
    paddingHorizontal: 2,
  },
  buyNowContainer: {
    width: '100%',
    height: 80,
    borderRadius: 10,
    borderColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 1,
    backgroundColor: '#FDEEDD',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginTop: 10,
    position: 'absolute',
    bottom: 0,
  },
  giaTienVaSoLuongContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  soLuongContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
   
    height: 'auto',

    marginHorizontal: 2,
    borderRadius: 12,
    borderColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 2,
    backgroundColor: '#FFECD2',
  },
  textSoLuong: {
    fontSize: 16,
    color: 'black',
    fontWeight: 'bold',
  },
  soLuongVaNutTuyChinhContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  textMuaNgay: {
    fontSize: 20,
    color: 'white',
    fontWeight: 'bold',
  },
  muaNgayButtonContainer: {
    width: '90%',
    height: 50,
    borderRadius: 10,
    borderColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 1,
    backgroundColor: BACKGROUND_BUTTON_COLOR,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  muaNgayContainer: {
    position: 'absolute',
    bottom: 5,
    width: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionHeaderContainer: {
    backgroundColor: '#FCDCAE',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderWidth: 0.1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  itemContainer: {
    padding: 6,
    margin: 6,
    backgroundColor: '#eee',
  },
  required: {
    fontSize: 15,
    color: 'red',
  },
  buttonSoLuong: {
    width: 'auto',
    height: 'auto',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderColor: BACKGROUND_BUTTON_COLOR,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
