import { StyleSheet, Text, View } from 'react-native'
import React from 'react'

export const styles = StyleSheet.create({

    container: {
        padding: 24,
        backgroundColor: '#FFFFF',
    },
    navhd: {
        display: "flex",
        justifyContent: "space-between",
        flexDirection: 'row'
    },
    thd: {
        color: '#000',
        fontFamily: "Inter",
        fontSize: 30,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 31,
        letterSpacing: 0.16,
    },
    iconhd: {
        fontSize: 30,
        color: 'black',
    },
    t1: {
        marginTop: 42,
        width: 132,
        height: 16,
        flexShrink: 0,
        color: '#000',
        fontFamily: "Inter",
        fontSize: 14,
        fontStyle: "normal",
        fontWeight: "500",
        lineHeight: 15,
    },
    t2: {
        marginTop: 29,
        width: 132,
        height: 16,
        flexShrink: 0,
        color: '#000',
        fontFamily: "Inter",
        fontSize: 14,
        fontStyle: "normal",
        fontWeight: "500",
        lineHeight: 15,
    },
    tip1: {
        padding: 10,
        display: "flex",
        width: "100%",
        height: 47,
        flexDirection: "column",
        justifyContent: "center",
        color: "#5B5B5B",
        fontFamily: "Inter",
        fontSize: 16,
        fontStyle: "normal",
        fontWeight: "400",
        lineHeight: 21,
        letterSpacing: 0.16,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#000',

    },
    vp: {
        position: 'relative'
    },
    icon: {
        display: "flex",
        position: 'absolute',
        alignSelf: "flex-end",
        margin: 5,
        right: 5,
        fontSize: 30,
    },
    btn1: {
        backgroundColor: "#D97700",
        display: "flex",
        width: "100%",
        height: 48,
        flexDirection: "column",
        justifyContent: "center",
        borderRadius: 10,
        alignSelf: "center",
        marginTop: 10,
        marginTop: 47,
    },
    txtbtn1: {
        color: "#FFFF",
        textAlign: "center",
        fontFamily: "Inter",
        fontSize: 20,
        fontStyle: "normal",
        fontWeight: "700",
        lineHeight: 21,
        letterSpacing: 0.16,
    },
})