import {StyleSheet} from 'react-native';
import {BACKGROUND_BUTTON_COLOR} from '../../../../utils/contanst';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  imageSanPham: {
    width: '100%',
    height: 250,
  },
  textTenSanPham: {
    fontSize: 30,
    color: 'black',
    fontWeight: '500',
  },
  thongTinSanPhamContainer: {
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'flex-start',
    width: '100%',
    height: 130,
    paddingLeft: 10,
    borderBottomEndRadius: 10,
    borderBottomStartRadius: 10,
    paddingRight: 10,
    borderColor: '#F3962C',
    borderWidth: 1,

    // backgroundColor: '#F3962C',
    backgroundColor: '#FCE0C0',
  },
  voteContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  danhMucContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 'auto',
    height: 'auto',
    padding: 5,
    marginHorizontal: 2,
    borderRadius: 10,
    backgroundColor: BACKGROUND_BUTTON_COLOR,
  },
  textDanhMuc: {
    fontSize: 15,
    color: 'white',
    fontWeight: '500',
  },
  baSizeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  space: {
    height: 2,
  },
  start: {
    fontSize: 14,
    color: 'black',
    fontWeight: '400',
  },
  danhSachDanhMucContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
    height: 'auto',
  },
  textMoTa: {
    fontSize: 18,
    color: 'black',
    fontWeight: '500',
    marginTop: 10,
    marginBottom: 5,
  },
  textThongTin: {
    fontSize: 15,
    color: '#404040',
    fontWeight: '400',
    paddingVertical: 2,
    width: 400,
  },
  textSize: {
    fontSize: 16,
    color: BACKGROUND_BUTTON_COLOR,
    fontWeight: 'bold',
  },
  textSizeSelected: {
    fontSize: 16,
    color: 'white',
    fontWeight: 'bold',
  },
  separateLine: {
    height: 1,
    width: '95%',
    backgroundColor: 'gray',
    marginVertical: 10,
  },
  sizeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 'auto',
    height: 'auto',
    paddingVertical: 5,
    paddingHorizontal: 25,
    marginHorizontal: 5,
    borderRadius: 12,
    borderColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 1.5,
    backgroundColor: '#FFECD2',
  },
  sizeSelectedContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 'auto',
    height: 'auto',
    paddingVertical: 5,
    paddingHorizontal: 25,
    marginHorizontal: 5,
    borderRadius: 12,
    borderColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 1.5,
    backgroundColor: BACKGROUND_BUTTON_COLOR,
  },
  chonSizeContainer: {
    width: '100%',
    paddingLeft: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  moTaContainer: {
    marginLeft: 10,
  },
  buyNowContainer: {
    width: '100%',
    height: 130,
    borderRadius: 10,
    borderColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 1,
    backgroundColor: '#FDEEDD',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginTop: 10,
    position: 'absolute',
    bottom: 0,
  },
  soLuongContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: 150,
    height: 'auto',
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginHorizontal: 2,
    borderRadius: 12,
    borderColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 2,
    backgroundColor: '#FFECD2',
  },
  textSoLuong: {
    fontSize: 16,
    color: BACKGROUND_BUTTON_COLOR,
    fontWeight: 'bold',
  },
  textSale: {
    fontSize: 18,
    color: BACKGROUND_BUTTON_COLOR,
    fontWeight: 'bold',
  },
  textTien: {
    fontSize: 18,
    color: 'gray',
    fontWeight: 'bold',
  },
  amount: {
    textDecorationLine: 'line-through', // Add a line-through text decoration
  },
  giaTienContainer: {
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 2,
    width: '100%',
    marginLeft: 15,
  },
  dash: {
    fontSize: 16,
    color: 'gray',
    paddingHorizontal: 5,
  },
  buyNowButtonContainer: {
    width: 130,
    height: 50,
    borderRadius: 10,
    borderColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 2,
    backgroundColor: BACKGROUND_BUTTON_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textBuyNow: {
    fontSize: 18,
    color: 'white',
    fontWeight: 'bold',
  },
  giaTienVaSoLuongContainer: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  containerSanPhamDeXuat: {
    flexDirection: 'column',
    width: 80,
    marginHorizontal: 12,
    marginTop: 10,
  },
  imageSanPhamDeXuat: {
    width: 80,
    height: 80,
  },
  textTenSanPhamDeXuat: {
    fontSize: 14,
    color: 'black',
    fontWeight: '500',
  },
  textGiaTienSanPhamDeXuat: {
    fontSize: 13,
    color: 'black',
    fontWeight: '400',
    color: BACKGROUND_BUTTON_COLOR,
  },
  sanPhamDeXuatContainer: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginLeft: 10,
    marginTop: 15,
  },
  buttonMuaSanPham: {
    position: 'absolute',
    bottom: 10,
    right: 5,
    width: 'auto',
    height: 'auto',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 50,
    backgroundColor: BACKGROUND_BUTTON_COLOR,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textMua: {
    fontSize: 15,
    color: 'white',
    fontWeight: '600',
    marginRight: 5,
  },
  backButton:{
    position: 'absolute',
    top: 5,
    left: 5,
    width: 'auto',
    height: 'auto',
    paddingHorizontal: 15,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: BACKGROUND_BUTTON_COLOR,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  }
});
