import {StyleSheet} from 'react-native';
import {BACKGROUND_BUTTON_COLOR} from '../../../utils/contanst';

export const editProfileStyle = StyleSheet.create({
  container: {
    // flexDirection: 'column',
    // justifyContent:'center',
    // alignItems: 'center',
    paddingHorizontal: 10,
    paddingBottom: 20,
  },
  imageProfile: {
    width: 200,
    height: 200,
    // marginVertical: 40,
    borderRadius: 100,
    alignSelf: 'center',
  },
  inputContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: BACKGROUND_BUTTON_COLOR,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    borderWidth: 1.5,
  },
  inputContainerWrong: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#FF0900',
    borderRadius: 8,
    paddingHorizontal: 10,
    borderWidth: 2.5,
  },
  icon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    height: 40,
    color: 'blue',
  },
  textLableInput: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    marginBottom: 5,
  },
  textLableInputWrong: {
    fontSize: 14,
    fontWeight: '400',
    color: 'red',
    fontStyle: 'italic',
  },
  textInputContainer: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginBottom: 30,
  },
  buttonSaveProfile: {
    width: '95%',
    height: 46,
    backgroundColor: BACKGROUND_BUTTON_COLOR,
    borderRadius: 10,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    // position: 'absolute',
    bottom: 10,
    alignSelf: 'center',
  },
  textSaveProfile: {
    fontSize: 20,
    fontWeight: '600',
    lineHeight: 26,
    letterSpacing: 0.3,
    textAlign: 'center',
    color: 'white',
  },
  camera: {
    position: 'absolute',
    bottom: 0,
    right: '25%',
    borderRadius: 50,
    padding: 5,
  },
  library: {
    position: 'absolute',
    bottom: 0,
    left: '25%',
    borderRadius: 50,
    backgroundColor:'transparent',
    padding: 5,
  },
});
